---
title: "Untitled"
author: "Elio Campitelli"
date: "April 4, 2017"
output:
    ioslides_presentation: 
        fig_height: 5
        fig_width: 9
        smaller: yes
        widescreen: yes
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE,
    cache = TRUE,
    cache.path = "cache/"
)
library(ncdf4)
source("scripts/helperfun.R")
month.abb <- c("Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep",
               "Oct", "Nov", "Dic")
names(month.abb) <- as.character(1:12)

theme_elio <- theme_minimal() + 
    theme(legend.position = "bottom")
theme_set(theme_elio)
coord_map_polar <- coord_map("stereographic", orientation = c(-90,0, 60),
                             ylim = c(-90, -20))

map.world.3 <- BuildMap(res = 3, smooth = 3, pm = 180)
map.SH.3 <- geom_map2(map.world.3[lat %b% c(-90, 0)])
map.world.3 <- geom_map2(map.world.3)
interp.levs <- exp(seq(log(925), log(30), length.out = 40))
```


## Amplitud de la onda 3

```{r}
# Leo datos de geopotencial de NCEP.

gh <- ReadNCEP("DATA/NCEP/hgt.mon.mean.nc", var = "hgt") %>%
    melt(value.name = "gh") %>%
    setDT() %>%
    .[lat <= 20 & lat != -90] %>%
    .[, date1 := as.Date(date[1], format = "%Y-%m-%d"), by = .(date)] %>%
    .[, date := NULL] %>%
    setnames("date1", "date")

# Calculo la onda 3
qs <- gh[, FitQsWave(gh, 3), by = .(lat, lev, date)]
qs.mean <- qs[, lapply(.SD, mean), by = .(lat, lev, month(date), k)]

qs.int <- qs.mean[, Interpolate.DT(amplitude, lat, lev, yo = interp.levs), 
                  by = .(month, k)]
qs.int[, r2 := qs.mean[, Interpolate.DT(r2, lat, lev, yo = interp.levs), 
                       by = .(month, k)][, r2]]
qs.int[, phase := qs.mean[, Interpolate.DT(phase, lat, lev, yo = interp.levs), 
                          by = .(month, k)][, phase]]
levs.sp <- ncvar_get(nc_open("DATA/SPEEDY/attm.nc"), "lev")
levs.index <- c(700, 300, 100)
```

```{r}
g <- ggplot(qs.mean[k == 3], aes(lat, lev)) +
    geom_contour(aes(z = amplitude), binwidth = 15, color = "black") +
    scale_x_reverse() + scale_y_continuous(trans = "reverselog", breaks = levs.sp, minor_breaks = NULL) +
    directlabels::geom_dl(aes(z = amplitude, label = ..level..), 
                          stat = "contour", color = "black", 
                          binwidth = 15, method = "top.pieces") +
    scale_fill_distiller(direction = 1) +
    ylab("Nivel") + xlab("Latitud") +
    annotate(geom = "segment", x = rep(-40, 3), xend = rep(-65, 3), 
             y = levs.index, yend = levs.index, color = "gray45", linetype = 2)

g + facet_grid_paginate(month~., page = 1, ncol = 1, nrow = 3, labeller = labeller(month = month.abb))
```

## Amplitud de la onda 3

```{r}
g + facet_grid_paginate(month~., page = 2, ncol = 1, nrow = 3, labeller = labeller(month = month.abb))
```

## Amplitud de la onda 3

```{r}
g + facet_grid_paginate(month~., page = 3, ncol = 1, nrow = 3, labeller = labeller(month = month.abb))
```

## Amplitud de la onda 3

```{r}
g + facet_grid_paginate(month~., page = 4, ncol = 1, nrow = 3, labeller = labeller(month = month.abb))
```

## 

Para construir el índice tomo --por ahora-- el promedio de la amplitud de la onda 3 en los niveles 700, 300 y 100 entre 65º y 40ºS (línea punteada anterior).

```{r}
lats <- unique(qs$lat)
lats.index <- lats[lats <= -40 & lats >= -65]
qs_index <- qs[lev %in% levs.index & lat %in% lats.index, 
               .(amplitude = mean(amplitude),
                 r2 = mean(r2),
                 phase = mean(phase)), 
               by = date]
```

```{r}
g <- ggplot(qs_index, aes(date, amplitude)) +
    geom_line() +
    scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
    ylab("Amplitud") + xlab("Fecha")

DivideTimeseries(g, n = 3, qs_index$date, ylab = "Amplitud", xlab = "Fecha")
```


## Ciclo anual

```{r}
Tercile <- function(x) {
  r <- quantile(x, probs = c(0.025, 1/3, 0.5, 2/3, 0.975))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
} 
qs_index[, quantile := ecdf(amplitude)(amplitude), by = month(date)]
ggplot(qs_index, aes(month(date), amplitude, group = month(date))) +
    geom_point(data = qs_index[quantile >= 0.975 | quantile <= 0.025]) +
    stat_summary(fun.data = Tercile, geom = "boxplot", position = "dodge") +
    scale_x_continuous(labels = month.abb, breaks = 1:12, name = "Mes") +
    ylab("Amplitud") +
    labs(caption = "líneas: 95%\ncajas: terciles")

```


## Usando R2 como índice

```{r}
g <- ggplot(qs_index, aes(date, r2)) +
    geom_line() +
    scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
    ylab("Amplitud") + xlab("Fecha")

DivideTimeseries(g, n = 3, qs_index$date, ylab = "R2", xlab = "Fecha")
```

## Ciclo anual de R^2

```{r}
qs_index[, quantile.r2 := ecdf(r2)(r2), by = month(date)]
ggplot(qs_index, aes(month(date), r2, group = month(date))) +
    geom_point(data = qs_index[quantile.r2 >= 0.975 | quantile.r2 <= 0.025]) +
    stat_summary(fun.data = Tercile, geom = "boxplot", position = "dodge") +
    scale_x_continuous(labels = month.abb, breaks = 1:12, name = "Mes") +
    ylab("R2") +
    labs(caption = "líneas: 95%\ncajas: terciles")

```

## Amplitud vs. R^2

```{r}
ggplot(qs_index, aes(r2, amplitude)) + 
    geom_point(alpha = 0.3) + 
    geom_smooth(method = "lm", se = F, linetype = 2, color = "black")  +
    xlab("R^2") + ylab("Amplitud")
```


# Composición de Geopotencial usando percentil 66 de la amplitud (lineas = 15 mgp)

----

```{r}
gh <- gh[qs_index, on = "date"]
gh.composition <- gh[, .(gh = mean(gh[quantile >= 2/3]) - mean(gh)), 
                     by = .(lon, lat, lev, month(date))]
```

```{r, fig.height=7, fig.width=10}
PlotTemp <- function(lev.plot) {
    ggplot(gh.composition[lev == lev.plot], aes(lon, lat)) +
        geom_contour(aes(z = gh, linetype = as.factor(-sign(..level..))), 
                     color = "black", binwidth = 15) +
        coord_map_polar + 
        facet_wrap(~month, nrow = 3, labeller = labeller(month = month.abb)) +
        map.SH.3 +
        scale_linetype(guide = FALSE) +
        labs(subtitle = paste0("nivel = ", lev.plot))
}

PlotTemp(100)
```
 
----

```{r, fig.height=7, fig.width=10}
PlotTemp(300)
```

----

```{r, fig.height=7, fig.width=10}
PlotTemp(700)
```

# Composición de Geopotencial usando percentil 66 de R^2 (lineas = 15 mgp)


```{r}
gh.composition.r2 <- gh[, .(gh = mean(gh[quantile.r2 >= 2/3]) - mean(gh)), 
                     by = .(lon, lat, lev, month(date))]
```

```{r, fig.height=7, fig.width=10}
PlotTemp <- function(lev.plot) {
    ggplot(gh.composition.r2[lev == lev.plot], aes(lon, lat)) +
        geom_contour(aes(z = gh, linetype = as.factor(-sign(..level..))), 
                     color = "black", binwidth = 15) +
        coord_map_polar + 
        facet_wrap(~month, nrow = 3, labeller = labeller(month = month.abb)) +
        map.SH.3 +
        scale_linetype(guide = FALSE) +
        labs(subtitle = paste0("nivel = ", lev.plot))
}

PlotTemp(100)
```
 
----

```{r, fig.height=7, fig.width=10}
PlotTemp(300)
```

----

```{r, fig.height=7, fig.width=10}
PlotTemp(700)
```
