---
title: "Teis"
subtitle: "Una tesis"
author: "Elio Campitelli"
date: "`r Sys.Date()`"
output:
    pdf_document:
        citation_package: natbib
        latex_engine: xelatex
        toc: true
        pandoc_args: [
        "-V", "lang=es-AR"
    ]
bibliography: skeleton.bib
link-citations: yes
---
 
```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, 
                      cache.extra = packageVersion('tufte'),
                      echo = FALSE)
options(htmltools.dir.version = FALSE)
```


Por ahora esto es un outline y no mucho más. 

Numerar las cosas. Figuras relevantes para cada sección. 

# Introducción

## Motivación

Algo más substancioso que "me interesa la gran escala y el clima de altas latitudes" :P 

* Efectos en nuestra región. 
* Analogía con estudios en el hemisferio norte. 

## Conceptos básicos

* Ondas cuasiestacionarias
* Fluos de activdiad de onda
 
## Antecedentes

* Quintanar y Mechoso, Raphael, et. al. 

## Hipótesis

¿Tengo una?

## Métodos

Descripción de los experimentos. 

## Fuentes de datos

## Modelo SPEEDY

# Climatología observada

## Campos medios y anomalías. 




## Ondas Quasiestacionarias

* Fourier

* Onda 1 a 4. 
* Amplitud, r2, etc...
* Fase. 

* Wavelets
   + Comparación.

Venajas y desventajas. Justificaicón de decisión. 

## Creación del índice

## Antecedentes

Breve comentario sobre los índices usados en otros lados. Discutir ventajas y debilidades.

* Amplitud
* Fase (impacto en SA) 

De todo eso, motiva decisión del índice.

## Índice propio

* Niveles elegidos
* Promedio vs. máximo
* Composiciones de campos y flujos.
* Decisión del índice. 

## Análisis dinámica de septiembre



## Fuentes de actividad de onda

## Fuentes de variabilidad interna

(Discusión escrita más de papers), Pero nos concentramos en la fuente externa.

## Fuentes externas

Campos de correlación con SST y OLR, principalmente
¿Discusión de otros forzantes?

# Experimentos

## Validación SPEEDY

* Comparación campos medios. 
* Validación de las corridas experimentales (mostrar que es constante lo que tiene que ser consante)

## Comparación 

Comparación entre corridas y ncep.

## Cosas inesperadas...

* ?? 
* protif!

# Conclusiones

# Agradecimientos

# Referencias


